volumes/app/upimage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # new
from django.conf.urls.static import static  # new


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("upimg.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

volumes/app/upimg/urls.py
from django.urls import path, include, reverse_lazy
from .views import(
    HomeView,
    CreateImageView, 
    SignupView, 
    LoginView, 
    DetailHomeView,
    DownloaddetailView,
    download_image,
    # LogoutView,
)
from django.conf import settings  # new
from django.conf.urls.static import static 
from django.contrib.auth.views import (
    LoginView,
    LogoutView, 
    PasswordResetView,
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from upimg import views
from django.contrib.auth import views as auth_views 

app_name = "upimg"
urlpatterns = [

    path('', HomeView.as_view(), name='home'),
    path('add/', CreateImageView.as_view(), name='add' ),
    path('<int:pk>/', DetailHomeView.as_view(), name='detail' ),
    path('<int:pk>/download/', download_image, name='download_image'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.SignupView, name="register"),
    path('password_reset/', PasswordResetView.as_view(template_name='registration/password_reset.html', 
    html_email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done1'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
    success_url=reverse_lazy('upimg:password_reset_complete')),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
]














    # path('login/', UserLoginAPIView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    # path('register/', views.SignupView, name="register"),
    # path(r'^api-token-auth/', obtain_jwt_token),
    # path(r'^api-token-refresh/', refresh_jwt_token),
    # path(r'^api-token-verify/', verify_jwt_token),
    # path(r'^register/$', UserCreateAPIView.as_view(), name='register'),


    

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

volumes/app/upimg/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.





class Image(models.Model):
    photo = models.ImageField(upload_to='images/%m-%Y/', verbose_name='تصویر')
    title = models.CharField(verbose_name='عنوان تصویر', max_length=100)
    publish = models.DateTimeField(auto_now=True, verbose_name='تاریخ')   
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name="imageup", verbose_name='ارسال کننده')
    def __str__(self):
        return self.title



class CustomUser(AbstractUser):
    username = models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')
    def __str__(self):
        return self.username

volumes/app/upimg/forms.py
from .models import Image
from django import forms
from django.forms import ModelForm 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ( 'title', 'photo','user')


class LoginForm(forms.Form):
    user_email = forms.EmailField(max_length=100)
    password   = forms.CharField(max_length=100)

class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = [ 'username', 'password1', 'password2']

volumes/app/upimg/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Image
from .forms import ImageForm
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings  # new
from . import forms
from django.contrib.auth import login
from django.views.generic import ListView, CreateView, DetailView
from django.contrib import messages
from django.contrib.auth import get_user_model

# Create your views here.

class HomeView(ListView):
    model = Image
    template_name = 'home.html'

class DetailHomeView(DetailView):
    model = Image
    template_name = 'detail.html'
    def get_queryset(self):
        return self.model.objects.filter(
            user=self.request.user,
            id=self.kwargs['pk']
        )
class DownloaddetailView(View):
    def get(self, request, *args, **kwargs):
        image = Image.objects.get(pk=self.kwargs['pk'])
        image_buffer = open(image.photo.url, "rb").read()
        content_type = magic.from_buffer(image_buffer, mime=True)
        response = HttpResponse(image_buffer, content_type=content_type);
        response['Content-Disposition'] = 'attachment; filename="%s"' % os.path.basename(image.photo.url)
        return response


def download_image(request, pk):
    # Assuming you have a model named Image with a FileField named 'image'
    image = get_object_or_404(Image, pk=pk)
    image_path = image.photo.url

    # Open the image file
    with open(image_path, 'rb') as f:
        response = FileResponse(f)
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(os.path.basename(image_path))
        return response


class CreateImageView(CreateView):
    model = Image
    form_class = ImageForm
    template_name = 'image_create.html'
    success_url = reverse_lazy('home')

class LoginView(View, LoginRequiredMixin):
    template_name = 'registrations/login.html'
    form_class = forms.LoginForm
    def get(self, request):
        form = self.form_class
        message = ''
        return render(request, self.template_name, context={ 'form': form, 'message':message})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = athenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                
            )
            if user is not None:
                login(request, user)
                return redirect('home')
        else:
            message = 'Login failed!'
        return render(request, self.template_name, context={'form': form, 'message':message})


# User = get_user_model()
def SignupView(request):
    form  = forms.RegistrationForm()
    if request.method == 'POST':
        form = forms.RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'شما با موفقیت ثبت نام شده اید.')
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            messages.error(request, 'نام کاربری شما معتبر نیست')
    else:
        form  = forms.RegistrationForm()
    return render(request, 'registration/register.html', context={'form': form})

volumes/app/upimg/templates/upimg/detail.html
{% extends 'home.html' %}
{% load static %}
{% load ratings %}
{% block content %}
<html>
 <style>
   img {
      width: 80%;
      float: left;
      margin-right: 20px;
   }
    .text1 {
      float: right;
      margin-right: 1000px;
      margin-top: 50px;
   } 
   .text {
    float: right;
    margin-right: 900px;
    margin-top: 50px;
 } 
</style>
<div class="text1">
<h2>{{ object.title }}</h2>
</div>
    <img src="{{ object.photo.url }}" />

<div class="text">
   {% ratings object %}

   <h3>{{ object.user }}</h3>
   <p>{{ object.publish }}<br/></p>
   <a href="{% url 'upimg:download_image' pk=object.pk %}">Download Image</a>

 
</div> 
{% endblock content %}

volumes/app/upimg/templates/upimg/home.html
{% load static %}
<link rel="stylesheet" type="text/css" href="/static/css/style1.css">
<br/>
<hr/>
{% block content %}
	{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul> 
     {% endif %}
{% if user.is_authenticated %}
    <a href="{% url 'upimg:logout' %}" class="button">خروج</a>
{% else %}
    <a href="{% url 'upimg:register' %}" class="button ml-5" mt-4>ثبت نام</a>
    <a href="{% url 'upimg:login' %}" class="button">ورود</a>
{% endif %}
<table>
    <tr>
        {% for img in object_list %}
            
            <td>
                <h2>{{ img.title }}</h2>
                <p> {{img.user }} </p>
                <a href= "{% url 'upimg:detail' img.id %}"/>  <img src="{{ img.photo.url }}" alt="{{ img.title }}"></a>
            </td>
            {% if forloop.counter|divisibleby:3 %}
                </tr><tr>
            {% endif %}
        {% endfor %}
    </tr>
</table>    
{% endblock content %}
 </html>

volumes/app/upimg/templates/upimg/image_create.html
{% load crispy_forms_tags %}

<br/>
<h2 dir='rtl'> افزودن تصویر</h2>
<form method="post" enctype="multipart/form-data" dir='rtl'  >
  <br/>
  {% csrf_token %}
  {{ form|crispy }}
  <br/>
  <button dir='ltr' type="submit">ارسال</button>
</form>